on: push
name: CI
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: Install
      run: npm install
    - name: Upload node_modules
      uses: actions/upload-artifact@v1
      with:
        name: node_modules
        path: node_modules/
    env:
      CI: true
  lint:
    needs: install
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: Download node_modules
      uses: actions/download-artifact@v1
      with:
        name: node_modules
    - name: Lint
      run: npm run lint
    env:
      CI: true
  court_basics:
    needs: install
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: Download node_modules
      uses: actions/download-artifact@v1
      with:
        name: node_modules
    - name: Court Basics
      run: npm test test/treasury/court-treasury.js test/court/court-{draft,gas}.js
    env:
      CI: true
  court_disputes:
    needs: install
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: Download node_modules
      uses: actions/download-artifact@v1
      with:
        name: node_modules
    - name: Court Disputes
      run: npm test test/court/court-{disputes,voting,appeal,confirm-appeal}.js
    env:
      CI: true
  court_settle_rounds:
    needs: install
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: Download node_modules
      uses: actions/download-artifact@v1
      with:
        name: node_modules
    - name: Court Settle Rounds
      run: npm test test/court/court-settle-round.js
    env:
      CI: true
  court_settle_appeals:
    needs: install
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: Download node_modules
      uses: actions/download-artifact@v1
      with:
        name: node_modules
    - name: Court Settle Appeals
      run: npm test test/court/court-settle-appeal.js
    env:
      CI: true
  registry:
    needs: install
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: Download node_modules
      uses: actions/download-artifact@v1
      with:
        name: node_modules
    - name: Registry
      run: npm test test/registry/*.js
    env:
      CI: true
  lib:
    needs: install
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: Download node_modules
      uses: actions/download-artifact@v1
      with:
        name: node_modules
    - name: Lib
      run: npm test test/lib/*.js
    env:
      CI: true
  voting:
    needs: install
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: Download node_modules
      uses: actions/download-artifact@v1
      with:
        name: node_modules
    - name: Voting
      run : npm test test/voting/*.js
    env:
      CI: true
  subscriptions:
    needs: install
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: Download node_modules
      uses: actions/download-artifact@v1
      with:
        name: node_modules
    - name: Subscriptions
      run: npm test test/subscriptions/*.js
    env:
      CI: true
  controller:
    needs: install
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: Download node_modules
      uses: actions/download-artifact@v1
      with:
        name: node_modules
    - name: Controller
      run: npm test test/controller/*.js
    env:
      CI: true
